# Generated by Django 6.0.5 on 2026-05-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdb',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdb',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
    ]
