services:
  - type: web
    name: lung-cancer-detection
    runtime: python
    rootDir: backend/proj1
    buildCommand: |
      cd ../../frontend && npm install && npm run build
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn proj1.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: CI
        value: "false"

